---
- name: Install base packages
  become: true
  apt:
    name: {{ item.name }}
    # update_cache: yes
    state: present
    loop: package_list

- name: Remove packages
  become: true
  apt:
    name:
      - screenfetch
      - glances
    state: absent

- name: Check if vifm theme exists
  stat:
    path: ~/.config/vifm/colors/solarized-dark.vifm
  register: stat_vifm_theme_result

- name: Creates config directory for vifm
  file:
    path: ~/.config/vifm/colors/
    state: directory
    recurse: true
  when: not stat_vifm_theme_result.stat.exists

- name: Download vifm theme
  get_url:
    url: https://raw.githubusercontent.com/vifm/vifm-colors/master/solarized-dark.vifm
    dest: ~/.config/vifm/colors/solarized-dark.vifm
#  when: not stat_vifm_theme_result.stat.exists

- name: create .vifmrc config file
  template:
    src: vifmrc.j2
    dest: ~/.config/vifm/vifmrc
    backup: true
    mode: 'u=rw,go=r'

- name: create .vimrc config file
  template:
    src: vimrc.j2
    dest: ~/.vimrc
    backup: true
    mode: 'u=rw,go=r'

# ZSH
- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Cloning oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists

- name: Check oh-my-zsh folder owner
  file:
    path: '~/.oh-my-zsh'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    recurse: true

- name: Cloning zsh-autosuggestions
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions
    dest=~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  #when: not stat_oh_my_zsh_result.stat.exists

- name: Cloning zsh-syntax-highlighting
  git:
    repo=https://github.com/zsh-users/zsh-syntax-highlighting
    dest=~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  #when: not stat_oh_my_zsh_result.stat.exists

- name: create zsh maccan theme
  template:
    src: maccan.zsh-theme.j2
    dest: ~/.oh-my-zsh/custom/themes/maccan.zsh-theme
    backup: true
    mode: 'u=rw,go=r'

- name: create .zshrc
  template:
    src: zshrc.j2
    dest: ~/.zshrc
    backup: true
    mode: 'u=rw,go=r'

- name: set default shell for users
  become: true
  user:
    name: '{{ ansible_user }}'
    shell: /bin/zsh
