---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Remove snap packages
  become: true
  community.general.snap:
    name: "{{ item }}"
    state: absent
  loop: "{{ snap_packages }}"
  when: ansible_facts.services["snapd.service"].state == 'running' 

- name: Shutdown snapd services, sockets and timers
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  failed_when: false
  loop:
    "{{ snapd_services }}"
